jobs:

  deployment:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://ansible.io/api/v2/job_templates/84/launch/'
        method: 'POST'
        username: ${{ secrets.AWX_USER }}
        password: ${{ secrets.AWX_PASSWORD }}
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"key_1": "value_1", "key_2": "value_2"}'
        
    - name: Make Request
      id: myRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: "http://yoursite.com/api"
        
    - name: Show Response
      run: |
        echo ${{ steps.myRequest.outputs.response }}
        echo ${{ steps.myRequest.outputs.headers }}
        echo ${{ fromJson(steps.myRequest.outputs.response).field_you_want_to_access }}
