name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  deployment:
  
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://example.com/'
        method: 'GET'
        
    - name: Make Request
      id: myRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: "http://example.com"
        
    - name: Show Response
      run: |
        echo ${{ steps.myRequest.outputs.response }}
        echo ${{ steps.myRequest.outputs.headers }}
        echo ${{ fromJson(steps.myRequest.outputs.response).field_you_want_to_access }}
