# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
#  container-test-job:
#    runs-on: ubuntu-latest
#    services:
#      service-name-1:
#        image: my-image-test:latest
#        ports:
#           - "8000:8000"
#
#      service-name-2:
#        image: tof974/web-api-docker:latest
#        ports:
#           - 8001:8000
           
#      service-name-3:
#        image: tof974/data-api-docker:latest
#        ports:
#           - 8002:8000

#    steps:
#      - name: Get from service-1
#        run: "curl -X GET https://example.com"

#      - name: Get from service-2
#        run: http://localhost:8001


#      - name: post a user example
#        run: "curl -x POST http://localhost:3001/api/user -H 'Content-Type: application/json' -d '{\"username"\: \"hello"\, \"address"\: "sampleaddress"}' "

  app-test-job:

    runs-on: ubuntu-latest
#
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check Model Prediction function
      run: pytest -v -m TestScripts/checkMainAppFunctions.py::testModelPrediction
      #TestScripts/checkMainAppFunctions.py::testModelPrediction
